[settings]
experimental = true

[tools]
biome = "2.3.14"
rust = "1.93.0"
sqlite = "3.51.2"
bun = "1.3.9"

[tasks.engine-clippy]
description = "Run Clippy for the engine crate"
run = "cargo clippy --workspace --all-targets --all-features -- -D warnings"
dir = "apps/engine"

[tasks.engine-test]
description = "Run engine test suite"
run = "cargo test --tests -- --test-threads=1"
dir = "apps/engine"
