[settings]
experimental = true

[tools]
bun = "1.3.9"
biome = "2.3.14"
rust = "1.93.0"

[tasks.clippy]
description = "Run Clippy for the engine crate"
run = "cargo clippy --workspace --all-targets --all-features -- -D warnings"
dir = "apps/engine"
